// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4P7MRCj3AQcI74c1DYEqRON4s3r4gp8',
    appId: '1:375071653374:web:dbc22f474cc6ad47004f4f',
    messagingSenderId: '375071653374',
    projectId: 'ai-fitness-trainer-10e3d',
    authDomain: 'ai-fitness-trainer-10e3d.firebaseapp.com',
    storageBucket: 'ai-fitness-trainer-10e3d.firebasestorage.app',
    measurementId: 'G-HFQHML8790',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ4P7MRCj3AQcI74c1DYEqRON4s3r4gp8',
    appId: '1:375071653374:android:dbc22f474cc6ad47004f4f',
    messagingSenderId: '375071653374',
    projectId: 'ai-fitness-trainer-10e3d',
    storageBucket: 'ai-fitness-trainer-10e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4P7MRCj3AQcI74c1DYEqRON4s3r4gp8',
    appId: '1:375071653374:ios:dbc22f474cc6ad47004f4f',
    messagingSenderId: '375071653374',
    projectId: 'ai-fitness-trainer-10e3d',
    storageBucket: 'ai-fitness-trainer-10e3d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4P7MRCj3AQcI74c1DYEqRON4s3r4gp8',
    appId: '1:375071653374:macos:dbc22f474cc6ad47004f4f',
    messagingSenderId: '375071653374',
    projectId: 'ai-fitness-trainer-10e3d',
    storageBucket: 'ai-fitness-trainer-10e3d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4P7MRCj3AQcI74c1DYEqRON4s3r4gp8',
    appId: '1:375071653374:web:dbc22f474cc6ad47004f4f',
    messagingSenderId: '375071653374',
    projectId: 'ai-fitness-trainer-10e3d',
    authDomain: 'ai-fitness-trainer-10e3d.firebaseapp.com',
    storageBucket: 'ai-fitness-trainer-10e3d.firebasestorage.app',
    measurementId: 'G-HFQHML8790',
  );
}